Added needed functionalities for chat
IrinaButu2307/FriendlyChat pull request #1
Opened 2019-05-27 19:17 UTC by andreihrs

Checkout these changes I've made. Let me know if there's anything wrong/needed.

2019-05-27 19:22 UTC, IrinaButu2307 commented
That seems very nice! You really simplified a lot of the code!

2019-05-28 18:06 UTC, AndreiOvidiuCiobanu requested changes

2019-05-28 18:06 UTC, AndreiOvidiuCiobanu commented on app/src/main/java/com/google/firebase/codelab/friendlychat/MainActivity.java
>      @Override
@anamariacercel how about implementing unit testing for this method? I think you should do a great job!

2019-05-28 18:07 UTC, anamariacercel commented on app/src/main/java/com/google/firebase/codelab/friendlychat/MainActivity.java
>      @Override
For sure! I will upload it in a short time.

2019-05-28 18:12 UTC, merged